name: Weekly schedule

on:
  workflow_dispatch:

jobs:
  trigger:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
    - name: Get Chrome version
      id: chromium
      timeout-minutes: 5
      shell: bash
      run: |
        VERSION="129.0.6666.0"
        BUILD=$(echo "$VERSION" | cut -d. -f3)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "branch=chromium/$BUILD" >> $GITHUB_OUTPUT
    - name: Get date
      id: date
      run: |
        echo "day=$(date +%-d)" >> $GITHUB_OUTPUT
    - name: Trigger build
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Build all
        inputs: |
          {
            "branch": "${{ steps.chromium.outputs.branch }}",
            "version": "${{ steps.chromium.outputs.version }}",
            "is_debug": "false",
            "release": "true",
            "nuget": "true",
            "anaconda": "${{ steps.date.outputs.day <= 7 && 'true' || 'false' }}"
          }
